# Generated by Django 2.2 on 2021-12-03 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20211117_1623'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='availabe',
            new_name='available',
        ),
    ]
